### ISSUE TITLE
巨巨，跪求解。关于coolq-telegram-bot

### ISSUE THREAD

**Issue by ghost** [jqqqqqqqqqq/BeihangLogin#1]
https://github.com/jqqqqqqqqqq/coolq-telegram-bot
这个项目没有issues页面，只好发在这里了。

coolq已经跑起来了，私聊QQ机器人也有反应。
telegram的bot也建立了。填写了token和tg群ID。
bot_constant.py也修改过了。

TOKEN = '45??????????????????????Lk'
QQ_BOT_ID = 3???????????0
FORWARD_LIST = [
    {
        'QQ': 17???????????5,
        'TG': -1001???????78,
        'Drive_mode': False,
        'Pic_link': False
    },
    {
        'QQ': 17?????????5,
        'TG': -1001??????????78,
        'Drive_mode': False,
        'Pic_link': False
    },
]
SERVER_PIC_URL = 'http://example.com:8080/image/'
CQ_ROOT = '/root/coolq-data/'
CQ_PORT = 11235
JQ_MODE = False  # if use Coolq Pro, set as True, otherwise False

然而转发bot运行起来没有效果？原因不明，我应该检查哪里啊？

**Comment by jqqqqqqqqqq** [comment]
不好意思，没注意到没开issue，你重新发一个过去吧，我把它开开了
