### ISSUE TITLE
CURLOPT_SSL_VERIFYHOST no longer supports 1 as value!

### ISSUE THREAD

**Issue by Arbitersc** [jqqqqqqqqqq/BeihangLogin#4]
when i run script with 'login' or 'logout', it returns me the information:
**login:**
```AC_ID: 
Challenge: 
Client IP: 
md5: Option -hmac needs a value
md5: Use -help for summary.
Encrypted PWD: 
Encrypted Info: OtdhoA1xnEJKP4ul5eBXiKCoyzIPohTIzN/g4nBzvfjGOxU5PKZMDE1l1nvpIguusAF1KzBugc4an1/7TP9uXZipr02gYsbVKtRPsnIvJVjNAeGSYmXZOo33viL=
Checksum: 010462910177c2d259142a68588820b023d1975d
curl: (43) CURLOPT_SSL_VERIFYHOST no longer supports 1 as value!
```

**logout:**
```AC_ID: 
Challenge: 
Client IP: 
curl: (43) CURLOPT_SSL_VERIFYHOST no longer supports 1 as value!
```

there are something wrong, but i dont know where. 
Thank you.

**Comment by z3dd1cu5** [comment]
In your case, this script didn't obtain `Challenge` successfully. There may be some problems in your network or the options of `curl`.

Please check:
1. Access https://gw.buaa.edu.cn in your web browser to examine your network.
2. Run `curl -h` to see whether your `curl` support `-k` option (which allows insecure SSL connection) and confirm how to use it. Some machines work well even without `-k`, but the SSL certification of https://gw.buaa.edu.cn is actually ill. Try to change the options of `curl` until a 64-character challenge code appears.
3. If methods above don't solve your problem, please offer us feedback reporting your device info, OS with version number, and other information for diagnosing.
